controllers/ContentController.php
<?php

namespace app\controllers;

use app\models\MContent;

class ContentController extends \yii\web\Controller
{
    public function actionIndex()
    {
        return $this->render('index');
    }

    public function actionView($type = '')
    {
        $data = MContent::find()->where(['type' => $type])->one();

        return $this->render('view', [
            'data' => $data
        ]);
    }

    public function actionProfile()
    {
        return $this->render('profile');
    }

    public function actionStakeholders()
    {
        return $this->render('stakeholders');
    }

    public function actionSocialMedia()
    {
        return $this->render('social_media');
    }

    public function actionLpsCreavid2022()
    {
        return $this->render('lps_creavid_2022');
    }

    public function actionJingleLikeIt()
    {
        return $this->render('jingle_like_it');
    }

    public function actionLikeIt1()
    {
        return $this->render('like_it_1');
    }

    public function actionLikeIt2()
    {
        return $this->render('like_it_2');
    }

    public function actionLikeIt3()
    {
        return $this->render('like_it_3');
    }

    public function actionLikeIt4()
    {
        return $this->render('like_it_4');
    }

    public function actionGaleriLikeIt2021()
    {
        return $this->render('galeri_like_it_2021');
    }

    public function actionGaleriLikeIt2022()
    {
        return $this->render('galeri_like_it_2022');
    }

    public function actionGaleriLikeIt2023()
    {
        return $this->render('galeri_like_it_2023');
    }

    public function actionGaleriLikeIt2024()
    {
        return $this->render('galeri_like_it_2024');
    }
}

controllers/EventController.php
<?php

namespace app\controllers;

use app\components\Helpers;
use app\models\BelumKirim;
use app\models\MContent;
use app\models\MMailTemplate;
use app\models\TCertificateRequest;
use app\models\TQuestion;
use app\models\TQuiz;
use app\models\TRegistration;
use app\models\TRegistrationSearch;
use Yii;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use Da\QrCode\QrCode;
use Da\QrCode\Format\BookmarkFormat;
use yii\web\UploadedFile;
use kartik\mpdf\Pdf;
use Mpdf\Mpdf;

// use ImageKit\ImageKit;  
/**
 * EventController implements the CRUD actions for TRegistration model.
 */

// const SCRIPT_URL = 'https://script.google.com/macros/s/AKfycbwdw55aQVKo3y_HJ4qkuYJP-brLVZYF5KrPxRICQz-1-XC6lTkfahy6MpybsWrOqqzWbw/exec';
const SCRIPT_URL = 'https://script.google.com/macros/s/AKfycby8xeTzayr-GwJyQcE1RSzhqW3xsvoolQR2bmAaAiHMJofBzLXEuTpQMpIBAIvJsnXxKg/exec';


class EventController extends Controller
{
    /**
     * @inheritDoc
     */
    public function behaviors()
    {
        return array_merge(
            parent::behaviors(),
            [
                'verbs' => [
                    'class' => VerbFilter::className(),
                    'actions' => [
                        'delete' => ['POST'],
                    ],
                ],
            ]
        );
    }

    /**
     * Lists all TRegistration models.
     *
     * @return string
     */
    public function actionIndex()
    {
        $searchModel = new TRegistrationSearch();
        $dataProvider = $searchModel->search($this->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single TRegistration model.
     * @param int $id ID
     * @return string
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new TRegistration model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return string|\yii\web\Response
     */
    public function actionCreate()
    {
        $model = new TRegistration();

        if ($this->request->isPost) {
            if ($model->load($this->request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            }
        } else {
            $model->loadDefaultValues();
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    public function actionRegistrasi($direct_invite = 0)
    {
      

        $model = new TRegistration();

        if ($this->request->isPost) {
            $post = $this->request->post();
            $now = date('Y-m-d H:i:s');
            $model->created_at = $now;

            if ($model->load($post) && $model->save()) {

                $body = $post['TRegistration'];
                $body['tanggal'] = $now;

                // $this->postToGoogleSheet('https://script.google.com/macros/s/AKfycbwlq8T_5uX0KepWkG1sLex3FyX05vWNDO1z1o0ZuThosvSyrAggSSvgp-l4weDvu6MO/exec', $body);

                return $this->redirect(['thanks']);
            }
        } else {
            $model->loadDefaultValues();
        }

        $check = MContent::find()->where(['type' => 'form_registrasi'])->one();

        if ($check->content == 'coming_soon') {
            return $this->render('coming_soon', []);
        } else if ($check->content == 'closed') {
            return $this->render('closed', [
                'type' => 'Pendaftaran'
            ]);
        } else if ($check->content == 'open') {
            return $this->render('registrasi', [
                'model' => $model,
                'direct_invite' => $direct_invite
            ]);
        }
    }

    public function actionSendRegistration()
    {
        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;

        $post = Yii::$app->request->post();
        if ($post) {
            $model = new TRegistration();
            $body = $post['TRegistration'];

            $check = TRegistration::find()->where(['no_ktp' => $body['no_ktp']])->one();
            if (!empty($check)) {
                // return [
                //     'success' => false,
                //     'message' => 'Nomor KTP sudah terdaftar.'
                // ];
            }

            $now = date('Y-m-d H:i:s');
            $model->load($post);
            $model->created_at = $now;
            $model->nama_lengkap = encrypt($body['nama_lengkap']);
            $model->email = encrypt($body['email']);
            $model->no_hp = encrypt($body['no_hp']);

            if ($model->save(false)) {

                $direct_invite = $post['direct_invite'];

                if ($direct_invite == '1') {

                    if (!empty($model)) {
                        $template = MMailTemplate::find()->where(['type' => 'undangan'])->one();
        
                        if (filter_var(decrypt($model->email), FILTER_VALIDATE_EMAIL)) {
                            $qrCode = (new QrCode('https://likeit.co.id/web/index.php/event/konfirmasi?e=' . $model->email))
                                ->setSize(250)
                                ->setMargin(5)
                                ->useForegroundColor(3, 39, 144);
        
                            $dir = dirname(__DIR__, 1) . '/web/images/code.png';
        
                            $qrCode->writeFile($dir);
        
                            $upload = $this->uploadImageKit($model->email);
        
                            if (!empty($upload)) {
                                $newTemplate = str_replace(['{nama_lengkap}', '{qr_code}'], [decrypt($model->nama_lengkap), $upload->url], $template->template);
                                $subject = $template->subject;
                                
        
                                $send = Yii::$app->mailer->compose()
                                    ->setFrom('no-reply@likeit.co.id')
                                    ->setTo(decrypt($model->email))
                                    ->setSubject($subject)
                                    ->setHtmlBody($newTemplate)
                                    ->send();
        
                                if ($send) {
        
                                    $model->status = 2;
                                    $model->updated_at = date('Y-m-d H:i:s');
                                    $model->save(false);
                                }
                            }
                        }
                    }
                }

                // $body = $post['TRegistration'];
                $body['tanggal'] = $now;

                // $this->postToGoogleSheet(SCRIPT_URL . '?sheet_name=Registrasi', $body);

                $data = [
                    'success' => true,
                ];
            } else {
                $data = [
                    'success' => false,
                    'message' => 'Gagal mengirim data pendaftaran, mohon coba beberapa saat lagi.'
                ];
            }

            return $data;
        }
    }

    public function actionCertificateRequest()
    {
        return $this->render('closed', []);

        $model = new TCertificateRequest();

        return $this->render('certificate_request', [
            'model' => $model,
        ]);
    }

    public function actionSendCertificateRequest()
    {
        set_time_limit(0);
        session_write_close();

        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;

        $post = Yii::$app->request->post();
        $foto = UploadedFile::getInstanceByName('TCertificateRequest[image]');

        if ($post) {
            $model = new TCertificateRequest();
            $body = $post['TCertificateRequest'];

            if ($foto->size > 2000000) {
                return $data = [
                    'success' => false,
                    'message' => "File melebihi ukuran maksimum 2Mb.",
                ];
            }

            if ($foto->type == 'image/png' || $foto->type == 'image/jpeg') {
                $upload = $this->uploadImageKit($body['email'], 'certificate_request', $foto->tempName);
                if (!empty($upload)) {
                    $now = date('Y-m-d H:i:s');
                    $body = $post['TCertificateRequest'];

                    $model->load($post);
                    $model->created_at = $now;
                    $model->image = $upload->url;
                    $model->nama_lengkap = encrypt($body['nama_lengkap']);
                    $model->email = encrypt($body['email']);
                    $model->no_hp = encrypt($body['no_hp']);
                    
                    if ($model->save(false)) {

                        $body['tanggal'] = $now;
                        $body['image'] = $upload->url;

                        // $this->postToGoogleSheet(SCRIPT_URL . '?sheet_name=Sertifikat', $body);

                        $data = [
                            'success' => true,
                            'message' => "Request berhasil, permintaan akan kami proses.",
                        ];
                    } else {
                        $data = [
                            'success' => false,
                            'message' => "Gagal melakukan request sertifikat, mohon coba beberapa saat lagi.",
                        ];
                    }
                } else {
                    $data = [
                        'success' => false,
                        'message' => "Gagal melakukan upload data",
                    ];
                }
            } else {
                $data = [
                    'success' => false,
                    'message' => "Format file tidak sesuai.",

views/layouts/login.php
<?php

/** @var yii\web\View $this */
/** @var string $content */

use app\assets\AppAsset;
use app\widgets\Alert;
use yii\bootstrap4\Breadcrumbs;
use yii\bootstrap4\Html;
use yii\bootstrap4\Nav;
use yii\bootstrap4\NavBar;
use yii\helpers\Url;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>" class="h-100">

<head>
  <meta charset="<?= Yii::$app->charset ?>">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


  <?php $this->registerCsrfMetaTags() ?>
  <title><?= Html::encode($this->title) ?></title>
  <?php $this->head() ?>
</head>

<body class="d-flex flex-column h-100" style="">
  <?php $this->beginBody() ?>
  <?php

  ?>
  <header>
    <nav class="navbar navbar-scrolled justify-content-between navbar-expand-md">

      <a class="navbar-brand" href="<?= Url::to(['/site/index']) ?>">
        <img class="navbar-logo" width="150px" src="<?= Yii::getAlias('@web') ?>/images/navbar_logo.png" alt="">
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <!-- <span class="navbar-toggler-icon"></span> -->
        <i class="fas fa-list" style="color: #fff;"></i>
      </button>
   
    </nav>

  </header>

  <main role="main" class="flex-shrink-0 main">
    <!-- <div class="container"> -->
    <!-- <img style="position: fixed;width: 100%;height: 100%;object-fit: cover;object-position: center;" src="https://ik.imagekit.io/d9hiweoihy/likeit/background.png?updatedAt=1691083353436" alt=""> -->
    <div class="h-100" style="margin-top: 85px;">
     
      <?= $content ?>
    </div>
  </main>

  <?php $this->endBody() ?>
</body>

</html>
<?php $this->endPage() ?>


<script>
  // $(function () {
  //     $(document).scroll(function () {
  //         var $nav = $(".navbar");
  //         $nav.toggleClass('navbar-scrolled', $(this).scrollTop() > $nav.height());
  //     });
  // });
</script>

views/layouts/main.php
<?php

/** @var yii\web\View $this */
/** @var string $content */

use app\assets\AppAsset;
use app\widgets\Alert;
use yii\bootstrap4\Breadcrumbs;
use yii\bootstrap4\Html;
use yii\bootstrap4\Nav;
use yii\bootstrap4\NavBar;
use yii\helpers\Url;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>" class="h-100">

<head>
  <meta charset="<?= Yii::$app->charset ?>">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


  <?php $this->registerCsrfMetaTags() ?>
  <title><?= Html::encode($this->title) ?></title>
  <?php $this->head() ?>
</head>

<body class="d-flex flex-column h-100" style="">
  <?php $this->beginBody() ?>
  <?php

  $menus = [
    ['id' => 'menu1', 'label' => 'Home', 'url' => '/site/index', 'children' => [], 'icon' => 'home'],
    // ['id' => 'menu1', 'label' => 'Game Password', 'url' => '/event/quiz', 'children' => []],
    ['id' => 'menu1', 'label' => 'Tentang', 'url' => '', 'children' => [
      ['label' => 'Profil LIKE IT', 'url' => '/content/profile'],
      ['label' => 'Stakeholders LIKE IT', 'url' => '/content/stakeholders'],
      ['label' => 'Social Media LIKE IT', 'url' => '/content/social-media'],
    ]],
    ['id' => 'menu2', 'label' => 'Agenda', 'url' => '', 'children' => [
      ['label' => 'LIKE IT #1', 'url' => '/content/like-it-1'],
      ['label' => 'LIKE IT #2', 'url' => '/content/like-it-2'],
      ['label' => 'LIKE IT #3', 'url' => '/content/like-it-3'],
      // ['label' => 'LIKE IT #4', 'url' => '/content/like-it-4'],
    ]],
    ['id' => 'menu3', 'label' => 'Galeri LIKE IT', 'url' => '', 'children' => [
      ['label' => 'Galeri LIKE IT 2021', 'url' => '/content/galeri-like-it-2021'],
      ['label' => 'Galeri LIKE IT 2022', 'url' => '/content/galeri-like-it-2022'],
      ['label' => 'Galeri LIKE IT 2023', 'url' => '/content/galeri-like-it-2023'],
      // ['label' => 'Galeri LIKE IT 2024', 'url' => '/content/galeri-like-it-2024'],
      ['label' => 'LPS CreaVid 2022', 'url' => '/content/lps-creavid-2022'],
      ['label' => 'Jingle LIKE IT 2021', 'url' => '/content/jingle-like-it'],
    ]],
    ['id' => 'menu4', 'label' => 'Registrasi', 'url' => '/event/registrasi', 'children' => []],
    
  ];

  ?>
  <header>
    <nav class="navbar navbar-scrolled justify-content-between navbar-expand-md">

      <a class="navbar-brand" href="<?= Url::to(['/site/index']) ?>">
        <img class="navbar-logo" width="150px" src="<?= Yii::getAlias('@web') ?>/images/navbar_logo.png" alt="">
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <!-- <span class="navbar-toggler-icon"></span> -->
        <i class="fas fa-list" style="color: #fff;"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown" style="justify-content: right;">
        <ul class="navbar-nav">
          <?php foreach ($menus as $key => $menu) : ?>
            <?php if (count($menu['children']) > 0) : ?>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="javascript:void(0)" id="<?= $menu['id'] ?>" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <?= $menu['label'] ?>
                </a>
                <div class="dropdown-menu my-0" aria-labelledby="<?= $menu['id'] ?>">
                  <?php foreach ($menu['children'] as $key => $child) : ?>
                    <a class="dropdown-item" href="<?= Url::to([$child['url']]) ?>"><?= $child['label'] ?></a>
                  <?php endforeach; ?>
                </div>
              </li>
            <?php else : ?>
              <li class="nav-item active">
                <a class="nav-link" href="<?= Url::to([$menu['url']]) ?>">
                  <?php if (!empty($menu['icon'])) : ?>
                    <i class="fas fa-<?= $menu['icon'] ?> mr-2"></i>
                  <?php endif; ?>
                  <?= $menu['label'] ?>
                </a>
              </li>
            <?php endif; ?>
          <?php endforeach; ?>
          <li class="nav-item">
                <a class="nav-link btn btn-survey" target="_blank" href="https://bit.ly/SurveiPraLikeIt2024">
                  Survey Investor
                </a>
              </li>
        </ul>
      </div>
    </nav>

  </header>

  <main role="main" class="flex-shrink-0 main">
    <!-- <div class="container"> -->
    <!-- <img style="position: fixed;width: 100%;height: 100%;object-fit: cover;object-position: center;" src="https://ik.imagekit.io/d9hiweoihy/likeit/background.png?updatedAt=1691083353436" alt=""> -->
    <div class="h-100" style="margin-top: 85px;">
      <!-- <?= Breadcrumbs::widget([
              'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
            ]) ?>
        <?= Alert::widget() ?> -->
      <?= $content ?>
    </div>
  </main>

  <footer style="margin-top: auto;position: relative;z-index: 1;">
    <img class="" src="https://ik.imagekit.io/d9hiweoihy/likeit/2024/Geometric%201.png?updatedAt=1719623724275" alt="" style="position: absolute;width: 100px;right: 0;top: 22px;">
    <img class="hidden-sm hidden-xs" src="https://ik.imagekit.io/d9hiweoihy/likeit/2024/KV_LIKE%20IT%202024_REV%201_4%20(3).png?updatedAt=1727363415940" alt="" style="position: absolute;width: 343px;left: -4px;bottom: 118px;">
    <div class="container">

      <div class="row d-flex justify-content-between " style="border-bottom: 2px solid #ccc6ea !important;">
        <div class="col-12 col-sm-4 col-md-2 col-lg-2 pt-4">
          <div class="row">
            <div class="col d-flex align-items-center">
              <!-- <img style="margin-left: auto; margin-right: auto;" src="https://ik.imagekit.io/d9hiweoihy/likeit/logo.png?updatedAt=1690531886657" alt="Logo LIKE IT" width="250px" height="auto"> -->
            </div>
          </div>
        </div>
        <div class="col-12 col-sm-8 col-md-8 col-lg-7 py-4">
          <div class="row">
            <div class="col-6 col-sm-4">
              <ul style="list-style: none; padding-left: 10px;">
                <li class="mb-4" style="font-size: 20px; font-weight: 600; color: #df0d90;">Navigation</li>
                <li><a href="<?= Url::to(['/site/index']) ?>">Home</a></li>
                <li><a href="<?= Url::to(['/content/profile']) ?>">Profil</a></li>
                <li><a href="<?= Url::to(['/content/stakeholders']) ?>">Stakeholders</a></li>
                <li><a href="<?= Url::to(['/event/registrasi']) ?>">Registrasi</a></li>
              </ul>
            </div>
            <div class="col-6  col-sm-4">
              <ul style="list-style: none; padding-left: 10px;">
                <li class="mb-4" style="font-size: 20px; font-weight: 600; color: #df0d90;">Agenda</li>
                <li><a href="<?= Url::to(['/content/like-it-1']) ?>">LIKE IT #1</a></li>
                <li><a href="<?= Url::to(['/content/like-it-2']) ?>">LIKE IT #2</a></li>
                <li><a href="<?= Url::to(['/content/like-it-3']) ?>">LIKE IT #3</a></li>
                <!-- <li><a href="<?= Url::to(['/content/like-it-4']) ?>">LIKE IT #4</a></li> -->
              </ul>
            </div>
            <div class="col-12  col-sm-4">
              <ul style="list-style: none; padding-left: 10px;">
                <li class="mb-4" style="font-size: 20px; font-weight: 600; color: #df0d90;">Galeri</li>
                <li><a href="<?= Url::to(['/content/galeri-like-it-2021']) ?>">LIKE IT 2021</a></li>
                <li><a href="<?= Url::to(['/content/galeri-like-it-2022']) ?>">LIKE IT 2022</a></li>
                <li><a href="<?= Url::to(['/content/galeri-like-it-2023']) ?>">LIKE IT 2023</a></li>
                <!-- <li><a href="<?= Url::to(['/content/galeri-like-it-2024']) ?>">LIKE IT 2024</a></li> -->
                <li><a href="<?= Url::to(['/content/lps-creavid-2022']) ?>">LPS Creavid 2022</a></li>
                <li><a href="<?= Url::to(['/content/jingle-like-it']) ?>">Jingle LIKE IT 2021</a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>

      <div class="row m-0 py-3 w-100">
        <div class="col-12 footer-socmed row d-flex justify-content-between d-flex align-items-center m-0">
          <div style="color: #de0e90;font-weight: 900;font-size: 20px;">&copy <?= date('Y') ?> LIKE IT</div>
          <div class="d-flex justify-content-center" style="gap: 20px;">
            <div class="p-1">
              <a target="_blank" href="https://www.bi.go.id">
                <i class="fas fa-globe" style="font-size: 25px;"></i>
              </a>
            </div>
            <div class="p-1">
              <a target="_blank" href="https://www.instagram.com/bank_indonesia/">
                <i class="fa-brands fa-2xl fa-instagram"></i>
              </a>
            </div>
            <div class="p-1">
              <a target="_blank" href="https://x.com/bank_indonesia">
                <i class="fa-brands fa-2xl fa-x-twitter"></i>
              </a>
            </div>
            <div class="p-1">
              <a target="_blank" href="https://www.youtube.com/channel/UCV7sYsOlkpbHybdIWt7gZbg">
                <i class="fa-brands fa-2xl fa-youtube"></i>
              </a>
            </div>
            <div class="p-1">
              <a target="_blank" href="https://web.facebook.com/BankIndonesiaOfficial">
                <i class="fa-brands fa-2xl fa-facebook"></i>
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>

  </footer>

  <?php $this->endBody() ?>
</body>

<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

</html>
<?php $this->endPage() ?>


<script>
  // $(function () {
  //     $(document).scroll(function () {
  //         var $nav = $(".navbar");
  //         $nav.toggleClass('navbar-scrolled', $(this).scrollTop() > $nav.height());
  //     });
  // });
</script>