controllers/EventController.php
<?php

namespace app\controllers;

use app\components\Helpers;
use app\models\BelumKirim;
use app\models\MContent;
use app\models\MMailTemplate;
use app\models\TCertificateRequest;
use app\models\TQuestion;
use app\models\TQuiz;
use app\models\TRegistration;
use app\models\TRegistrationSearch;
use Yii;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use Da\QrCode\QrCode;
use Da\QrCode\Format\BookmarkFormat;
use yii\web\UploadedFile;
use kartik\mpdf\Pdf;
use Mpdf\Mpdf;

// use ImageKit\ImageKit;  
/**
 * EventController implements the CRUD actions for TRegistration model.
 */

// const SCRIPT_URL = 'https://script.google.com/macros/s/AKfycbwdw55aQVKo3y_HJ4qkuYJP-brLVZYF5KrPxRICQz-1-XC6lTkfahy6MpybsWrOqqzWbw/exec';
const SCRIPT_URL = 'https://script.google.com/macros/s/AKfycby8xeTzayr-GwJyQcE1RSzhqW3xsvoolQR2bmAaAiHMJofBzLXEuTpQMpIBAIvJsnXxKg/exec';


class EventController extends Controller
{
    /**
     * @inheritDoc
     */
    public function behaviors()
    {
        return array_merge(
            parent::behaviors(),
            [
                'verbs' => [
                    'class' => VerbFilter::className(),
                    'actions' => [
                        'delete' => ['POST'],
                    ],
                ],
            ]
        );
    }

    /**
     * Lists all TRegistration models.
     *
     * @return string
     */
    public function actionIndex()
    {
        $searchModel = new TRegistrationSearch();
        $dataProvider = $searchModel->search($this->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single TRegistration model.
     * @param int $id ID
     * @return string
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new TRegistration model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return string|\yii\web\Response
     */
    public function actionCreate()
    {
        $model = new TRegistration();

        if ($this->request->isPost) {
            if ($model->load($this->request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            }
        } else {
            $model->loadDefaultValues();
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    public function actionRegistrasi($direct_invite = 0)
    {
      

        $model = new TRegistration();

        if ($this->request->isPost) {
            $post = $this->request->post();
            $now = date('Y-m-d H:i:s');
            $model->created_at = $now;

            if ($model->load($post) && $model->save()) {

                $body = $post['TRegistration'];
                $body['tanggal'] = $now;

                // $this->postToGoogleSheet('https://script.google.com/macros/s/AKfycbwlq8T_5uX0KepWkG1sLex3FyX05vWNDO1z1o0ZuThosvSyrAggSSvgp-l4weDvu6MO/exec', $body);

                return $this->redirect(['thanks']);
            }
        } else {
            $model->loadDefaultValues();
        }

        $check = MContent::find()->where(['type' => 'form_registrasi'])->one();

        if ($check->content == 'coming_soon') {
            return $this->render('coming_soon', []);
        } else if ($check->content == 'closed') {
            return $this->render('closed', [
                'type' => 'Pendaftaran'
            ]);
        } else if ($check->content == 'open') {
            return $this->render('registrasi', [
                'model' => $model,
                'direct_invite' => $direct_invite
            ]);
        }
    }

    public function actionSendRegistration()
    {
        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;

        $post = Yii::$app->request->post();
        if ($post) {
            $model = new TRegistration();
            $body = $post['TRegistration'];

            $check = TRegistration::find()->where(['no_ktp' => $body['no_ktp']])->one();
            if (!empty($check)) {
                // return [
                //     'success' => false,
                //     'message' => 'Nomor KTP sudah terdaftar.'
                // ];
            }

            $now = date('Y-m-d H:i:s');
            $model->load($post);
            $model->created_at = $now;
            $model->nama_lengkap = encrypt($body['nama_lengkap']);
            $model->email = encrypt($body['email']);
            $model->no_hp = encrypt($body['no_hp']);

            if ($model->save(false)) {

                $direct_invite = $post['direct_invite'];

                if ($direct_invite == '1') {

                    if (!empty($model)) {
                        $template = MMailTemplate::find()->where(['type' => 'undangan'])->one();
        
                        if (filter_var(decrypt($model->email), FILTER_VALIDATE_EMAIL)) {
                            $qrCode = (new QrCode('https://likeit.co.id/web/index.php/event/konfirmasi?e=' . $model->email))
                                ->setSize(250)
                                ->setMargin(5)
                                ->useForegroundColor(3, 39, 144);
        
                            $dir = dirname(__DIR__, 1) . '/web/images/code.png';
        
                            $qrCode->writeFile($dir);
        
                            $upload = $this->uploadImageKit($model->email);
        
                            if (!empty($upload)) {
                                $newTemplate = str_replace(['{nama_lengkap}', '{qr_code}'], [decrypt($model->nama_lengkap), $upload->url], $template->template);
                                $subject = $template->subject;
                                
        
                                $send = Yii::$app->mailer->compose()
                                    ->setFrom('no-reply@likeit.co.id')
                                    ->setTo(decrypt($model->email))
                                    ->setSubject($subject)
                                    ->setHtmlBody($newTemplate)
                                    ->send();
        
                                if ($send) {
        
                                    $model->status = 2;
                                    $model->updated_at = date('Y-m-d H:i:s');
                                    $model->save(false);
                                }
                            }
                        }
                    }
                }

                // $body = $post['TRegistration'];
                $body['tanggal'] = $now;

                // $this->postToGoogleSheet(SCRIPT_URL . '?sheet_name=Registrasi', $body);

                $data = [
                    'success' => true,
                ];
            } else {
                $data = [
                    'success' => false,
                    'message' => 'Gagal mengirim data pendaftaran, mohon coba beberapa saat lagi.'
                ];
            }

            return $data;
        }
    }

    public function actionCertificateRequest()
    {
        return $this->render('closed', []);

        $model = new TCertificateRequest();

        return $this->render('certificate_request', [
            'model' => $model,
        ]);
    }

    public function actionSendCertificateRequest()
    {
        set_time_limit(0);
        session_write_close();

        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;

        $post = Yii::$app->request->post();
        $foto = UploadedFile::getInstanceByName('TCertificateRequest[image]');

        if ($post) {
            $model = new TCertificateRequest();
            $body = $post['TCertificateRequest'];

            if ($foto->size > 2000000) {
                return $data = [
                    'success' => false,
                    'message' => "File melebihi ukuran maksimum 2Mb.",
                ];
            }

            if ($foto->type == 'image/png' || $foto->type == 'image/jpeg') {
                $upload = $this->uploadImageKit($body['email'], 'certificate_request', $foto->tempName);
                if (!empty($upload)) {
                    $now = date('Y-m-d H:i:s');
                    $body = $post['TCertificateRequest'];

                    $model->load($post);
                    $model->created_at = $now;
                    $model->image = $upload->url;
                    $model->nama_lengkap = encrypt($body['nama_lengkap']);
                    $model->email = encrypt($body['email']);
                    $model->no_hp = encrypt($body['no_hp']);
                    
                    if ($model->save(false)) {

                        $body['tanggal'] = $now;
                        $body['image'] = $upload->url;

                        // $this->postToGoogleSheet(SCRIPT_URL . '?sheet_name=Sertifikat', $body);

                        $data = [
                            'success' => true,
                            'message' => "Request berhasil, permintaan akan kami proses.",
                        ];
                    } else {
                        $data = [
                            'success' => false,
                            'message' => "Gagal melakukan request sertifikat, mohon coba beberapa saat lagi.",
                        ];
                    }
                } else {
                    $data = [
                        'success' => false,
                        'message' => "Gagal melakukan upload data",
                    ];
                }
            } else {
                $data = [
                    'success' => false,
                    'message' => "Format file tidak sesuai.",

views/event/_certificate_template.php
<style>
    .nama {
        font-family: Arial; font-size: 36px; color: #c77d7d; text-align: center; position: absolute; top: 270px; width: 100%;
    }

    .instansi {
        font-family: Arial; font-size: 20px; font-weight: bold; color: #000080; text-align: center; margin-top: 10px;
    }
</style>

<div style="height: 100%; width: 100%; position: relative; text-align: center; font-size: 24px;">
    <div class="nama"><?= $nama ?></div>
    <div class="instansi"><?= $instansi ?></div>
</div>

views/event/certificate_request.php
<?php

use app\components\Helpers;
use yii\captcha\Captcha;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;

$this->title = 'Request Sertifikat';

$model->event_id = 1;

$required = '<span style="color:red;">*</span>';

?>

<div class="main-content">
    <img class="img-left" style="" src="https://ik.imagekit.io/d9hiweoihy/likeit/2024/Geometric%201%20(1).png?updatedAt=1727364604511" alt="">
    <img class="img-right" style="" src="https://ik.imagekit.io/d9hiweoihy/likeit/2024/Geometric%201.png?updatedAt=1719623724275" alt="">
    <img class="img-city" src="https://ik.imagekit.io/d9hiweoihy/likeit/2024/Gedung-Gedung.png?updatedAt=1719623724320" alt="">
    <div class="container mb-5">
        <div class="card ">
            <div class="card-header">
                <h1 class=""><i class="fas fa-certificate"></i> Request Sertifikat</h1>
            </div>
            <div class="card-body">
                <?php $form = ActiveForm::begin([
                    'id' => 'cert-form'
                ]); ?>
                <?= $form->field($model, 'event_id')->hiddenInput()->label(false) ?>

                <div class="row">
                    <div class="col-md-12">
                    <div class="alert alert-success mb-5">
                        <i class="fa fa-info-circle"></i>
                        Formulir request sertifikat Diperpanjangan hingga <span>Jumat, 22 November 2024</span>
                    </div>
                    </div>
                    <div class="col-md-6">
                        <?= $form->field($model, 'nama_lengkap', ['template' => Helpers::inputIcon('user', $required)])->textInput(['maxlength' => '25', 'class' => 'form-control nlb', 'placeholder' => 'Maksimal 25 karakter']) ?>
                    </div>
                    <div class="col-md-6">
                        <?= $form->field($model, 'no_hp', ['template' => Helpers::inputIcon('phone')])->textInput(['maxlength' => true, 'class' => 'form-control nlb'])->label('No. Handphone (Opsional)') ?>
                    </div>
                    <div class="col-md-6">
                        <?= $form->field($model, 'email', ['template' => Helpers::inputIcon('at', $required)])->textInput(['maxlength' => true, 'class' => 'form-control nlb', 'id' => 'email-input']) ?>
                    </div>
                    <div class="col-md-6">
                        <?= $form->field($model, 'instansi', ['template' => Helpers::inputIcon('building', $required)])->textInput(['maxlength' => '35', 'placeholder' => 'Maksimal 35 karakter', 'class' => 'form-control nlb', 'id' => 'instansi-input']) ?>
                    </div>
                    <div class="col-md-6">
                        <!-- <?= $form->field($model, 'image', ['template' => Helpers::inputIcon('image', $required)])->textInput(['maxlength' => true, 'class' => 'form-control nlb']) ?> -->
                        <div class="form-group field-tcertificaterequest-image">

                            <label class="control-label" for="tcertificaterequest-image">Foto Bukti Kehadiran <?= $required ?></label> <span class="text-muted small ml-2" style="font-style: italic;">(Maksimal 2Mb dengan format JPG/JPEG/PNG)<span>
                                    <div class="input-group mb-1">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text"><i class="fa fa-image" aria-hidden="true"></i></span>
                                        </div>
                                        <input type="file" id="tcertificaterequest-image" class="form-control nlb" name="TCertificateRequest[image]">
                                    </div>
                                    <span class="text-muted small" style="font-style: italic;">Foto atau Capture menghadiri event LIKE It secara offline ataupun online<span>

                        </div>
                    </div>
                    <div class="col-md-12 text-center">
                        <div class="form-group text-center">
                            <div style="width: 200px;margin:auto;">
                                <div class="mb-3">
                                    <canvas class="mb-2" id="canvas" style="border: 1px solid #6f73ca;"></canvas>
                                    <input name="code" class="form-control">
                                </div>
                                <?= Html::button('Request Sertifikat', ['class' => 'btn btn-success btn-lg', 'id' => 'submit-form']) ?>
                            </div>
                        </div>
                    </div>
                </div>

                <?php ActiveForm::end(); ?>
            </div>
        </div>

    </div>
</div>
<img class="d-none" style="height: 28px;" src="//counter.websiteout.net/compte.php?S=likeit.co.id&C=17&D=0&N=88923&M=0" alt="" border="0" />

<script>
    const captcha = new Captcha($('#canvas'), {
        length: 4,
        resourceType: 'A',
    });

    $('#submit-form').click(function() {

        const check = captcha.valid($('input[name="code"]').val());

        const nama_lengkap = $('#tcertificaterequest-nama_lengkap').val()
        const email = $('#email-input').val()
        const image = $('#tcertificaterequest-image').val()

        const formInput = {
            "Nama Lengkap": nama_lengkap,
            "Email": email,
            "Foto Bukti Kehadiran": image,
        }

        for (const key in formInput) {
            if (Object.prototype.hasOwnProperty.call(formInput, key)) {
                const _inp = formInput[key];

                if (_inp == '') {
                    alert(`${key} wajib di isi`)
                    return false
                }
            }
        }

        if (!isEmail($('#email-input').val())) {
            alert('Email tidak valid')
            return false
        }

        if (check) {
            var formData = new FormData($('#cert-form')[0]);

            // $.ajax({
            //     url: `<?= Url::to(['/event/send-certificate-request']) ?>`,
            //     type: 'POST',
            //     dataType: 'JSON',
            //     data: formData,
            //     processData: false,
            //     contentType: false,
            //     beforeSend: function() {
            //         $('#submit-form').attr('disabled', true)
            //     },
            //     success: function(response) {
            //         if (response.success) {
            //             // alert('Terima kasih, kami telah menerima permintaan anda')
            //             Swal.fire({
            //                 title: "Terima kasih",
            //                 text: "kami telah menerima permintaan anda",
            //                 icon: "success",
            //                 showCancelButton: false,
            //                 confirmButtonColor: "#3085d6",
            //                 cancelButtonColor: "#d33",
            //                 confirmButtonText: "Ok"
            //                 }).then((result) => {
            //                     if (result.isConfirmed) {
            //                         window.open('https://forms.gle/nrnz7tcRwMTxT4ko9', '_blank')
            //                     }
            //                 });
            //             // $('#text-captcha').val('')
            //             $('#cert-form')[0].reset()
            //         } else {
            //             alert(response.message)
            //         }
            //     },
            //     complete: function() {
            //         $('#modal-detail').modal('hide');
            //         $('#submit-form').attr('disabled', false)

            //     },
            //     error: function(xhr, ajaxOptions, thrownError) {
            //         var pesan = xhr.status + " " + thrownError + "\n" + xhr.responseText;
            //         $('#modal-detail .modal-body').html(pesan);
            //         $('#submit-form').attr('disabled', false)

            //         // alert(pesan);
            //     }
            // });

            Swal.fire({
                title: 'Kirim Permintaan?',
                text: "Apakah Anda yakin ingin mengirim permintaan sertifikat?",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Ya, kirim!'
            }).then((result) => {
                if (result.isConfirmed) {
                    // Menampilkan loader sebelum request AJAX dimulai
                    Swal.fire({
                        title: 'Mengirim...',
                        text: 'Silakan tunggu beberapa saat.',
                        allowOutsideClick: false,
                        didOpen: () => {
                            Swal.showLoading();
                        }
                    });

                    $.ajax({
                        url: `<?= Url::to(['/event/send-certificate-request']) ?>`,
                        type: 'POST',
                        dataType: 'JSON',
                        data: formData,
                        processData: false,
                        contentType: false,
                        beforeSend: function() {
                            $('#submit-form').attr('disabled', true);
                        },
                        success: function(response) {
                            if (response.success) {
                                Swal.fire({
                                    title: "Terima kasih",
                                    text: "Kami telah menerima permintaan Anda",
                                    icon: "success",
                                    confirmButtonColor: "#3085d6",
                                    confirmButtonText: "Ok"
                                }).then((result) => {
                                    // if (result.isConfirmed) {
                                    //     window.open('https://forms.gle/nrnz7tcRwMTxT4ko9', '_blank');
                                    // }

                                    window.location.href = '<?= Url::to(['/site/index']) ?>'
                                });
                                $('#cert-form')[0].reset();
                            } else {
                                Swal.fire({
                                    title: "Gagal",
                                    text: response.message,
                                    icon: "error",
                                    confirmButtonColor: "#3085d6",
                                    confirmButtonText: "Ok"
                                });
                            }
                        },
                        complete: function() {
                            $('#modal-detail').modal('hide');
                            $('#submit-form').attr('disabled', false);
                        },
                        error: function(xhr, ajaxOptions, thrownError) {
                            var pesan = xhr.status + " " + thrownError + "\n" + xhr.responseText;
                            $('#modal-detail .modal-body').html(pesan);
                            $('#submit-form').attr('disabled', false);
                            Swal.fire({
                                title: "Error",
                                text: pesan,
                                icon: "error",
                                confirmButtonColor: "#3085d6",
                                confirmButtonText: "Ok"
                            });
                        }
                    });
                }
            });


        } else {
            alert('Captcha tidak sesuai')
        }

        captcha.refresh();
    })

    function isEmail(email) {
        var regex = /^([a-zA-Z0-9_.+-])+\@(([a-zA-Z0-9-])+\.)+([a-zA-Z0-9]{2,4})+$/;
        return regex.test(email);
    }
</script>

views/event/closed.php
<?php

use app\models\MContent;
use yii\helpers\Url;

$this->title = 'Event Closed';

?>

<div class="main-content">
<img class="img-left" style="" src="https://ik.imagekit.io/d9hiweoihy/likeit/2024/Geometric%201%20(1).png?updatedAt=1727364604511" alt="">
    <img class="img-right" style="" src="https://ik.imagekit.io/d9hiweoihy/likeit/2024/Geometric%201.png?updatedAt=1719623724275" alt="">
    <img class="img-city" src="https://ik.imagekit.io/d9hiweoihy/likeit/2024/Gedung-Gedung.png?updatedAt=1719623724320" alt="">
    <div class="container mb-5">

        <div class="card">
            <div class="card-header">
                <h1 class=""><?= $this->title ?></h1>
            </div>
            <div class="card-body text-center" style="">
                <h2 class="display-5">
                    <i class="fas fa-clock"></i>
                    <div>
                    <?= $type ?> telah di tutup, sampai jumpa di event berikutnya.
                    </div>
                </h2>
                <a href="<?= Url::to(['/site/index']) ?>" class="btn btn-success">
                <i class="fas fa-home"></i> Kembali ke halaman Utama</a>
            </div>
        </div>

    </div>
</div>

views/event/create.php
<?php

use yii\helpers\Html;

/** @var yii\web\View $this */
/** @var app\models\TRegistration $model */

$this->title = 'Create T Registration';
$this->params['breadcrumbs'][] = ['label' => 'T Registrations', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="tregistration-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/event/index.php
<?php

use app\models\TRegistration;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\ActionColumn;
use yii\grid\GridView;
use yii\widgets\Pjax;
/** @var yii\web\View $this */
/** @var app\models\TRegistrationSearch $searchModel */
/** @var yii\data\ActiveDataProvider $dataProvider */

$this->title = 'T Registrations';
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="main-content">
    <div class="container mb-5">
        <h1 class="display-4">List Register</h1>

        <div class="card">
            <div class="card-body text-black">
            <?php Pjax::begin(); ?>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            // 'id',
            'event_id',
            'nama_lengkap',
            'no_ktp',
            'email:email',
            'profesi',
            'instansi',
            'no_hp',
            'description:ntext',
            'status',
            'created_at',
            //'updated_at',
            //'deleted_at',
            [
                'class' => ActionColumn::className(),
                'urlCreator' => function ($action, TRegistration $model, $key, $index, $column) {
                    return Url::toRoute([$action, 'id' => $model->id]);
                 }
            ],
        ],
    ]); ?>

    <?php Pjax::end(); ?>
            </div>
        </div>

    </div>
</div>

views/event/konfirmasi.php
<?php

use app\components\Helpers;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;

/** @var yii\web\View $this */
/** @var app\models\TRegistration $model */

$this->title = 'Konfirmasi Kehadiran';


if (!empty($model)) {
   
    $model->nama_lengkap = decrypt($model->nama_lengkap);
    $model->email = decrypt($model->email);
    $model->no_hp = decrypt($model->no_hp);
}


?>

<div class="main-content">
<img class="img-left" style="" src="https://ik.imagekit.io/d9hiweoihy/likeit/2024/Geometric%201%20(1).png?updatedAt=1727364604511" alt="">
    <img class="img-right" style="" src="https://ik.imagekit.io/d9hiweoihy/likeit/2024/Geometric%201.png?updatedAt=1719623724275" alt="">
    <img class="img-city" src="https://ik.imagekit.io/d9hiweoihy/likeit/2024/Gedung-Gedung.png?updatedAt=1719623724320" alt="">
    <div class="container mb-5">
        <div class="card">
            <div class="card-body ">
                <?php if ($self == '1') : ?>
                    <div class="row mb-3">
                        <div class="col-12 col-md-8">
                            <div class="input-group mb-3">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="fa fa-user"></i></span>
                                </div>
                                <input type="text" class="form-control nlb" placeholder="Masukkan alamat email atau nomor KTP" name="" id="email-input">
                            </div>

                        </div>
                        <div class="col-12 col-md-4">
                            <button class="btn btn-success btn-lg btn-block" id="submit-form">Submit</button>
                        </div>
                    </div>
                <?php endif; ?>
                <?php if (!empty($_GET['e'])) : ?>

                    <h2 class="display-5 text-center">
                        <?= $success ? '<i class="fas fa-check-circle"  style="color: #00ae00;font-size: 80px;margin-bottom: 20px;"></i>' : '<i class="fas fa-times-circle" style="color: #ff3a3a;font-size: 80px;margin-bottom: 20px;"></i>' ?>
                        <div>
                            <?= $message ?>
                        </div>
                    </h2>
                <?php endif; ?>

                <?php if (!empty($model)) : ?>
                    <div>
                        <?php $form = ActiveForm::begin([
                            'id' => 'registrasi-form'
                        ]); ?>
                        <?= $form->field($model, 'event_id')->hiddenInput()->label(false) ?>
                        <div class="row">
                            <div class="col-md-6">
                                <?= $form->field($model, 'nama_lengkap', ['template' => Helpers::inputIcon('user')])->textInput(['maxlength' => true, 'class' => 'form-control nlb', 'disabled' => true]) ?>
                                <!-- <?= $form->field($model, 'no_ktp', ['template' => Helpers::inputIcon('id-card')])->textInput(['maxlength' => true, 'class' => 'form-control nlb', 'id' => 'ktp-input', 'disabled' => true]) ?> -->
                                <?= $form->field($model, 'email', ['template' => Helpers::inputIcon('at')])->textInput(['maxlength' => true, 'class' => 'form-control nlb', 'id' => 'email-input', 'disabled' => true]) ?>
                                <?= $form->field($model, 'no_hp', ['template' => Helpers::inputIcon('phone')])->textInput(['maxlength' => true, 'class' => 'form-control nlb', 'id' => 'no_hp', 'disabled' => true]) ?>
                            </div>
                            <div class="col-md-6">
                                <?= $form->field($model, 'profesi', ['template' => Helpers::inputIcon('briefcase')])->textInput(['maxlength' => true, 'class' => 'form-control nlb', 'disabled' => true]) ?>
                                <?= $form->field($model, 'instansi', ['template' => Helpers::inputIcon('building')])->textInput(['maxlength' => true, 'class' => 'form-control nlb', 'disabled' => true]) ?>
                                
                            </div>
                            <div class="col-md-12 text-center">
                                <?= $form->field($model, 'description')->textarea(['rows' => 6, 'disabled' => true]) ?>
                            </div>
                        </div>
                        <?php ActiveForm::end(); ?>
                    </div>
                <?php endif; ?>



            </div>
        </div>

    </div>
</div>

<script>
    $('#submit-form').click(function() {
        var email = $('#email-input').val()
        // if (!isEmail(email)) {
        //     alert('Email tidak valid')
        //     return false
        // }
        window.location.href = '<?= Url::to(['/event/konfirmasi', 'self' => '1']) ?>&e='+email
    })

    function isEmail(email) {
        var regex = /^([a-zA-Z0-9_.+-])+\@(([a-zA-Z0-9-])+\.)+([a-zA-Z0-9]{2,4})+$/;
        return regex.test(email);
    }
</script>

views/event/update.php
<?php

use yii\helpers\Html;

/** @var yii\web\View $this */
/** @var app\models\TRegistration $model */

$this->title = 'Update T Registration: ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'T Registrations', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="tregistration-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>